name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - pandas
  - pillow
  - ipywidgets
  - descartes
  - scipy
  - requests
  - folium
  - branca
  - chardet
  - pygeoif
  - pip:
      - ipython-magic-folium
      - ./packages/Localization.zip