name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy<2.0.0
  - matplotlib
  - pandas
  - pillow
  - ipywidgets
  - scipy
  - requests
  - pip:
      - ipython-magic-folium