name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - pandas
  - pillow
  - ipywidgets
  - descartes
  - scipy
  - pip:
      - requests
      - shapely
      - folium
      - ipython-magic-folium