project:
  type: website
website:
  title: "TM112 Location Based Computing"
  description: "Interactive demos using in-browser Pyodide/Python."
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd
      - section: TM112 Block 2 Part 6
        contents:
          - Activity_6.16_-_Cell_Tower_Lookup.qmd
          - Activity_6.20_-_Locating_Nearby_Wifi_Hotspots.qmd
          - Activity_6.22_-_6.25_-_Geocoding.qmd
          - Activity_6.27_-_Creating_annotated_interactive_maps_with_Python.qmd
          - Activity_6.29_-_Modelling_uncertainty_in_simple_trilateration.qmd
      - section: TM112 Block 3 Part 2
        contents:
          - Block_3_Part_2_-_Box_2.3_Looking_back_Geocoding_Demos.qmd
      - section: Bonus Content
        contents:
          - Bonus_notebook_-_Sonification_Demo.qmd
          - using_folium_magic_api.qmd


