---
title: Activity 6.29 Modeling Uncertainty
format: live-html
---

This notebook provides a simple interactive example of how the location and signal strength of three base stations can affect the amount of uncertainty associated with locating a receiver based on its relative distance from each of them.

__For the quarto book version of this page, the app needs updating to a shiny app... TO DO__

## Trilateration Demo

When you run the following cell you will be presented with several interactive sliders that let you set the *x, y* coordinates that define the location of three separate base stations.

The *r* value sets the distance over which the cell tower can be detected, modeled as the radius of a circle drawn around the corresponding cell tower.

The location of a target receiver is identified as a red dot. The dark blue area represents the uncertainty in locating the receiver based on its ability to see two or more of the cell towers.__Move the sliders to change the relative locations and ranges of each of the cell towers. See how it affects the uncertainty in determining location based on the ability to detect two or more cell towers and a knowledge of their locations.__

```{pyodide}
#| autorun: true
#| echo: false
print("Importing required Pyodide packages...")
import micropip
await micropip.install("localization-patched")
print("All necessary Pyodide packages loaded.")

```

```{pyodide}
# NOTE THAT THE WIDGETS USED IN THIS DEMO MAY NOT WORK IN THE INTERACTIVE TEXTBOOK VIEW
%pip install --quiet ipywidgets==8.1.1 matplotlib localization-patched

import tridash
```

You can look at the python code used to generate the interactive here: [tridash.py](tridash.py)

