name: Create HTML5 bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-file: build_environment.yml
          cache-environment: true
    
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        run: |
          cp README*.md content
          jupyter lite build --contents content --output-dir dist-tm112-jupyterlite

      - name: Patch JupyterLite for Moodle use
        run: |
          sed -i 's|<link rel="manifest" href="\([^"]*\)" />|<link rel="manifest" href="\1" crossorigin="use-credentials" />|' ./dist-tm112-jupyterlite/lab/index.html

      - name: Patch config-utils.js
        run: cp ./patches/config-utils.js ./dist-tm112-jupyterlite/config-utils.js
  
      # For Moodle, the html5.zip needs to see the index.html at the root
      # So create a zip file with no wrapper directory
      # that will unarchive the files at the current path.
      - name: Create the a JupyterLite.zip file
        run: |
          cd dist-tm112-jupyterlite
          zip -r ../tm112-jupyterlite-html5zip.zip . --exclude "*.git*"

      - name: Upload JupyterLite site artifact
        uses: actions/upload-artifact@v4
        with:
          name: tm112-jupyterlite-html5zip-distribution
          path: |
            dist-tm112-jupyterlite/
            !.git
            !.git/**
